server:
  port: 0

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8111/eureka

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 86400000