spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 86400000

logging:
  level:
    root: INFO
    com.dmatch.authservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

app:
  api-prefix: /api/v1
  internal-prefix: /internal

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        minimum-number-of-calls: 5
    instances:
      user-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true
    instances:
      user-service:
        base-config: default
        timeout-duration: 5s
