spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/job_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: debug

app:
  api-prefix: /api/v1
  internal-prefix: /internal

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        minimum-number-of-calls: 5
    instances:
      user-service:
        base-config: default
      company-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true
    instances:
      user-service:
        base-config: default
        timeout-duration: 5s
      company-service:
        base-config: default