spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: warn

app:
  api-prefix: /api/v1
  internal-prefix: /internal
  internal-service-key: ${INTERNAL_SERVICE_KEY:changeme-internal-key}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

openapi:
  service:
    title: User Service API
    version: 1.0.0
    url: http://localhost:8081